services:
  # ==========================================================
  # 1. APLICACIÓN PRINCIPAL: Goallet API
  # ==========================================================
  goallet-api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: goallet-api
    restart: unless-stopped
    ports:
      - "8080:8080" # API REST
      - "2112:2112" # Métricas Prometheus
    volumes:
      - ./app.log:/app/app.log # Montaje del archivo de log
    networks:
      - monitoring

  # ==========================================================
  # 2. PROMETHEUS (Métricas)
  # ==========================================================
  prometheus:
    image: prom/prometheus:v2.54.0
    container_name: goallet-prometheus
    restart: unless-stopped
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--web.enable-remote-write-receiver'
      - '--enable-feature=otlp-write-receive'
    ports:
      - '9090:9090'
    networks:
      - monitoring

  # ==========================================================
  # 3. LOKI (Logs)
  # ==========================================================
  loki:
    image: grafana/loki:3.0.0
    container_name: goallet-loki
    restart: unless-stopped
    command: -config.file=/etc/loki/local-config.yaml
    ports:
      - '3100:3100'
    networks:
      - monitoring

  # ==========================================================
  # 4. GRAFANA (Visualización)
  # ==========================================================
  grafana:
    image: grafana/grafana:11.1.0
    container_name: goallet-grafana
    restart: unless-stopped
    ports:
      - '3000:3000'
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_USERS_ALLOW_SIGN_UP=false
    volumes:
      - grafana-data:/var/lib/grafana
      - ./monitoring/grafana/provisioning:/etc/grafana/provisioning:ro
      - ./monitoring/grafana/dashboards:/var/lib/grafana/dashboards:ro
    networks:
      - monitoring
    depends_on:
      - prometheus
      - loki

  # ==========================================================
  # 5. ALLOY (Recolector de Telemetría)
  # ==========================================================
  alloy:
    image: grafana/alloy:v1.2.1
    container_name: goallet-alloy
    restart: unless-stopped
    ports:
      - '12345:12345'
    volumes:
      - ./config.alloy:/etc/alloy/config.alloy:ro
      - ./app.log:/var/log/app.log:ro
    command:
      - run
      - --server.http.listen-addr=0.0.0.0:12345
      - /etc/alloy/config.alloy
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - monitoring
    depends_on:
      - goallet-api
      - prometheus
      - loki

networks:
  monitoring:
    driver: bridge
volumes:
  grafana-data: